### ISSUE TITLE
Statuser i opprettelse av ny dialog burde sendes med

### ISSUE THREAD

**Issue by alexander-svendsen** [navikt/veilarbdialog#13]
Nå skjer de i forskjellige kall og dette kan skape problemer på serveren

**Comment by rfc3092** [comment]
Lukker denne pga. utløpsdato.

**Comment by alexander-svendsen** [comment]
Tja, kan fremdeles være relevant. Men er ikke noe viktig. Optional statuser som sendes med i opprettelse hadde vært nice :)
